config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "jobs#index"
  resources :jobs
  resources :rooms, only: [:new, :create, :destroy, :index] do
    resources :messages, only: [:index, :create]
  end
end

app/models/job.rb
class Job < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :category
  with_options presence:true, numericality: { other_than: 0 } do
    validates :prefecture_id
    validates :category_id
  end

  with_options presence:true do
    validates :order_title
    validates :order_detail
    validates :period
    validates :order_price
    validates :job_post_code
    validates :job_city
  end
  
  belongs_to :user  
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:edit, :update, :show, :destroy, :current]
  before_action :current, only: [:edit, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]
  

  def index
    @job = Job.all.order("created_at DESC")
    @job = Kaminari.paginate_array(@job).page(params[:page]).per(4)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if  @job.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @job.update(job_params) 
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def show
    @room = Room.new
  end

  def destroy
    if @job.destroy
      redirect_to root_path
    else
      render 'show'
    end
  end

  private

  def job_params
    params.require(:job).permit(:order_title, :order_detail, :period, :order_price, :category_id, :job_post_code, :prefecture_id, :job_city, :job_house_number, :building_name).merge(user_id: current_user.id)
  end

  def current
    redirect_to(root_url) unless @job.user_id == current_user.id
  end

  def set_job
    @job = Job.find(params[:id])
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/jobs/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @job, local: true) do |f| %>
      <p>仕事内容</p>
      <h5>必須</h5>
      <%= f.text_field :order_title, placeholder: "〇〇の電気工事" %>
      <p>仕事の詳細</p>
      <h5>必須</h5>
      <%= f.text_area :order_detail, placeholder: "〇〇の電気工事、○月○日に来れる方", rows: "10" %>
      <p>期間</p>
      <h5>必須</h5>
      <%= f.text_field :period, placeholder: "○月○日〜○月○日予定 詳細はチャットで連絡" %>
      <p>契約金額</p>
      <h5>必須</h5>
      <%= f.text_field :order_price, placeholder: "契約金額又は日当〇〇千円" %>
      <p>業種を指定</p>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"field"}) %>

      <p>現場の郵便番号</p>
      <h5>必須</h5>
      <%= f.text_field :job_post_code, placeholder: "111-111" %>
      <p>都道府県</p>
      <h5>必須</h5>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"field"}) %>
      <p>現場の市町村</p>
      <h5>必須</h5>
      <%= f.text_field :job_city, placeholder: "〇〇市" %>
      <p>現場の住所</p>
      <%= f.text_field :job_house_number, placeholder: "〇〇町1-1" %>
      <p>現場の建物名</p>
      <%= f.text_field :building_name, placeholder: "〇〇マンション101" %>

      <%= f.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="contents row">
  <% @job.each do |job| %>
    <body>
      <div class="main">
        <div class="main-header"></div>
        <div class="main-content">
          <div class="messages">
            <div class="message-title">
              <div class="message-body"><%=link_to job.order_title , job_path(job.id) %></div>
              <div class="more"></div>
            </div>
            <div class="message">
              <div class="message-name">①依頼者</div>
              <div class="message-body">
              <% if job.user.company_name != nil %>
                <%= job.user.company_name %>
              <% end  %>
              <%= job.user.name %></div>
            </div>
            <div class="message">
              <div class="message-name">②工事期間</div>
              <div class="message-body"><%= job.period %></div>
            </div>
            <div class="message">
              <div class="message-name">③現場</div>
              <div class="message-body"><%= job.job_city %></div>
            </div>
          </div>
        </div>
      </div>
    </body>
  <% end %>
  <%= paginate @job %>
</div>

app/views/jobs/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with(model: @job, local: true) do |f| %>
      <p>仕事内容</p>
      <h5>必須</h5>
      <%= f.text_field :order_title, placeholder: "〇〇の電気工事" %>
      <p>仕事の詳細</p>
      <h5>必須</h5>
      <%= f.text_area :order_detail, placeholder: "〇〇の電気工事、○月○日に来れる方", rows: "10" %>
      <p>期間</p>
      <h5>必須</h5>
      <%= f.text_field :period, placeholder: "○月○日〜○月○日予定 詳細はチャットで連絡" %>
      <p>契約金額</p>
      <h5>必須</h5>
      <%= f.text_field :order_price, placeholder: "契約金額又は日当〇〇千円" %>
      <p>業種を指定</p>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"field"}) %>

      <p>現場の郵便番号</p>
      <h5>必須</h5>
      <%= f.text_field :job_post_code, placeholder: "111-111" %>
      <p>都道府県</p>
      <h5>必須</h5>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"field"}) %>
      <p>現場の市町村</p>
      <h5>必須</h5>
      <%= f.text_field :job_city, placeholder: "〇〇市" %>
      <p>現場の住所</p>
      <%= f.text_field :job_house_number, placeholder: "〇〇町1-1" %>
      <p>現場の建物名</p>
      <%= f.text_field :building_name, placeholder: "〇〇マンション101" %>

      <%= f.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="contents row">
  <% if user_signed_in? %>
    <% if current_user.id == @job.user_id %>
      <ul class="btn-list">
        <li>
          <%= link_to '編集', edit_job_path(@job.id), method: :get ,class: 'btns' %>
        </li>
        <li>
          <%= link_to '削除', job_path(@job.id), method: :delete,class: 'btns' %>
        </li>
      </ul>
    <% end %>
  <% end %>
  <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">依頼者</th>
          <td class="detail-value"><%= @job.user.name %></td>
        </tr>
        <tr>
          <th class="detail-item">業種</th>
          <td class="detail-value"><%= @job.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">依頼内容</th>
          <td class="detail-value"><%= @job.order_title %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の詳細内容</th>
          <td class="detail-value"><%= @job.order_detail %></td>
        </tr>
        <tr>
          <th class="detail-item">工事予定期間</th>
          <td class="detail-value"><%= @job.period %></td>
        </tr>
        <tr>
          <th class="detail-item">契約金額または日当</th>
          <td class="detail-value"><%= @job.order_price %></td>
        </tr>
        <tr>
          <th class="detail-item">現場の郵便番号</th>
          <td class="detail-value"><%= @job.job_post_code %></td>
        </tr>
        <tr>
          <th class="detail-item">現場住所</th>
          <td class="detail-value"><%= @job.prefecture.name %><%= @job.job_city %><%= @job.job_house_number %><%= @job.building_name %></td>
        </tr>
      </tbody>
    </table>

    <%# チャット機能をつける %>
    <% if user_signed_in?  %>
      <% if current_user.id != @job.user.id %>
        <table class="detail-table">
          <tbody>   
            <tr>
              <th class="detail-item">      
                <p>契約内容を詳しく聞きたい方や質問がある方はこちらへ</p>
                <%= link_to '新規チャット', new_room_path %>
              </th>
            </tr>
          </tbody>
        </table>
      <% end %>
    <% else %>
      <table class="detail-table">
        <tbody>  
          <tr>
            <th class="detail-item">
              <%= link_to '契約内容などを詳しく聞きたい方はログインすることでチャットをご利用になれます。' ,new_user_session_path %>
            </th>
          </tr>
        </tbody>
      </table>
    <% end %>
</div>